name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd main
        cargo build --verbose
    - name: Run
      run: |
        cd main
        cargo test --verbose

  clean:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean
      run: |
        cd ./main/target
        cargo clean
